# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  # Ubuntu для окружения разработки
  config.vm.define "dev" do |dev|
    dev.vm.box = "bento/ubuntu-20.04"
    dev.vm.hostname = "dev"
    dev.vm.network "private_network", ip: "192.168.56.10"
    dev.vm.provision "ansible" do |ansible|
      ansible.playbook = "wordpress.yml"
      ansible.inventory_path = "ansible/env/dev/inventory"
      ansible.limit = 'all'
    end
  end

  # CentOS для окружения продакшена
  config.vm.define "prod" do |prod|
  config.vm.box = "generic/centos9s"
    prod.vm.hostname = "prod"
    prod.vm.network "private_network", ip: "192.168.56.11"
    prod.vm.provision "ansible" do |ansible|
      ansible.playbook = "wordpress.yml"
      ansible.inventory_path = "ansible/env/prod/inventory"
      ansible.limit = 'all'
    end
  end
end
