# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "dev" do |dev|
    dev.vm.box = "bento/ubuntu-20.04"
    dev.vm.hostname = "dev"
    dev.vm.network "private_network", ip: "192.168.56.10"
    dev.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/playbooks/site.yml"
      ansible.inventory_path = "ansible/env/dev/inventory"
    end
  end


  config.vm.define "prod" do |prod|
    prod.vm.box = "bento/ubuntu-20.04"
    prod.vm.hostname = "prod"
    prod.vm.network "private_network", ip: "192.168.56.11"
    prod.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/playbooks/site.yml"
      ansible.inventory_path = "ansible/env/prod/inventory"
    end
  end
end
