version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=admin_password
    networks:
      - jenkins_network

  maven-agent:
    image: jenkins/inbound-agent
    container_name: maven-agent
    environment:
      - JENKINS_AGENT_NAME=maven-agent
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_SECRET=5a10edab1e254db61fb3b90e6f2b58613866b3cb6adfbfb1b4c37ddc49d1857e
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins_network
    depends_on:
      - jenkins

volumes:
  jenkins_home:

networks:
  jenkins_network:
    driver: bridge
