---
- hosts: web
  become: true

  tasks:
    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - wget
        - htop
        - nginx

    - name: Start nginx service
      service:
        name: nginx
        state: started
        enabled: true

    - name: Display environment information
      debug:
        msg: "This host is in {{ ansible_hostname }} environment"
