apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  root-password: {{ .Values.mysql.rootPassword | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  db-password: {{ .Values.wordpress.dbPassword | b64enc }}